"use client";

import { useRef, useState, useEffect, ReactNode } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import mermaid from "mermaid";

let mermaidCounter = 0;

function ClickableVisual({ children }: { children: ReactNode }) {
  const [modalHtml, setModalHtml] = useState<string | null>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  const handleOpen = () => {
    if (contentRef.current) {
      setModalHtml(contentRef.current.innerHTML);
    }
  };

  return (
    <>
      <div
        ref={contentRef}
        onClick={handleOpen}
        className="cursor-pointer rounded-lg border border-gray-200 p-4 transition-all hover:border-blue-300 hover:shadow-md"
        title="Click to enlarge"
      >
        {children}
      </div>
      {modalHtml && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/30 backdrop-blur-sm"
          onClick={() => setModalHtml(null)}
        >
          <div
            className="relative max-h-[95vh] max-w-[95vw] overflow-auto rounded-2xl bg-white p-8 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setModalHtml(null)}
              className="sticky top-0 right-0 z-10 float-right rounded-full bg-white p-2 text-gray-500 shadow hover:bg-gray-100 hover:text-gray-700"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
            <div
              className="[&_svg]:h-auto [&_svg]:min-h-[50vh] [&_svg]:w-auto [&_svg]:scale-150 [&_svg]:origin-top-left [&_svg]:p-8"
              dangerouslySetInnerHTML={{ __html: modalHtml }}
            />
          </div>
        </div>
      )}
    </>
  );
}

function MermaidDiagram({ code }: { code: string }) {
  const [svg, setSvg] = useState("");
  const idRef = useRef(`mermaid-${++mermaidCounter}`);

  useEffect(() => {
    mermaid.initialize({ startOnLoad: false, theme: "neutral" });
    mermaid.render(idRef.current, code).then(({ svg }) => setSvg(svg));
  }, [code]);

  return (
    <ClickableVisual>
      <div dangerouslySetInnerHTML={{ __html: svg }} />
    </ClickableVisual>
  );
}

interface LessonContentProps {
  content: string;
}

export function LessonContent({ content }: LessonContentProps) {
  return (
    <article className="prose max-w-none prose-p:my-2 prose-headings:mt-6 prose-headings:mb-2 prose-ul:my-2 prose-li:my-0.5">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        // Security: rehype-raw passes all HTML through. Safe here because content is generated by Claude (trusted source).
        rehypePlugins={[rehypeRaw]}
        components={{
          code({ className, children, ...props }) {
            const match = /language-mermaid/.exec(className || "");
            if (match) {
              return <MermaidDiagram code={String(children).trim()} />;
            }
            return (
              <code className={className} {...props}>
                {children}
              </code>
            );
          },
          svg({ children, ...props }) {
            return (
              <ClickableVisual>
                <svg {...props}>{children}</svg>
              </ClickableVisual>
            );
          },
        }}
      >
        {content}
      </ReactMarkdown>
    </article>
  );
}
